// <auto-generated />
using HotelListing.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelListing.Migrations
{
    [DbContext(typeof(HotelListingContext))]
    [Migration("20211220045707_SeedingTestData")]
    partial class SeedingTestData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotelListing.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 110,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 2,
                            Code = 111,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 3,
                            Code = 112,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 4,
                            Code = 113,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 5,
                            Code = 114,
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 6,
                            Code = 115,
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 7,
                            Code = 116,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 8,
                            Code = 117,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 9,
                            Code = 118,
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 10,
                            Code = 119,
                            Name = "Finland"
                        });
                });

            modelBuilder.Entity("HotelListing.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Australia",
                            CountryId = 1,
                            Name = "Australia Hotel",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 2,
                            Address = "Belgium",
                            CountryId = 4,
                            Name = "Belgium Hotel",
                            Rating = 4.0999999999999996
                        },
                        new
                        {
                            Id = 3,
                            Address = "Bangladesh",
                            CountryId = 3,
                            Name = "Bangladesh Hotel",
                            Rating = 3.7999999999999998
                        },
                        new
                        {
                            Id = 4,
                            Address = "Canada",
                            CountryId = 7,
                            Name = "Canada Hotel",
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 5,
                            Address = "Denmark",
                            CountryId = 8,
                            Name = "Denmark Hotel",
                            Rating = 4.0
                        });
                });

            modelBuilder.Entity("HotelListing.Models.Hotel", b =>
                {
                    b.HasOne("HotelListing.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
